### ISSUE TITLE
ImportError: cannot import name 'lsd' from 'lsd'

### ISSUE THREAD

**Issue by dacrypt** [andrewdcampbell/OpenCV-Document-Scanner#12]
```
python3 scan.py --image sample_images/dollar_bill.JPG
Traceback (most recent call last):
  File "scan.py", line 20, in <module>
    from pylsd.lsd import lsd
  File "xx/Library/Python/3.8/lib/python/site-packages/pylsd/__init__.py", line 8, in <module>
    from lsd import lsd
ImportError: cannot import name 'lsd' from 'lsd' (/Users/david/Library/Python/3.8/lib/python/site-packages/lsd/__init__.py)
```

**Comment by whps40506** [comment]
pip install ocrd-fork-pylsd==0.0.3

After install that,  it shows "Implementation has been removed due original code license issues in function 'cv::LineSegmentDetectorImpl::LineSegmentDetectorImpl'"

pip install opencv-contrib-python

It worked for me😊

**Comment by Pancham1603** [comment]
just use `pip install -r requirements.txt`
