### ISSUE TITLE
ModuleNotFoundError: No module named 'lsd'

### ISSUE THREAD

**Issue by lucasleirbag** [andrewdcampbell/OpenCV-Document-Scanner#19]
I am encountering an error when trying to run the script scan.py in my project. The error occurs when trying to import the lsd module from the pylsd package. I received the following error:

```
Traceback (most recent call last):
  File "/Users/mac/Project/OpenCV-Document-Scanner/scan.py", line 20, in <module>
    from pylsd.lsd import lsd
  File "/Users/mac/Project/OpenCV-Document-Scanner/venv/lib/python3.11/site-packages/pylsd/__init__.py", line 8, in <module>
    from lsd import lsd
ModuleNotFoundError: No module named 'lsd'
```

Environment:

    Operating System: MacOS
    Python Version: 3.11.9

**Comment by seb5433** [comment]
Hi there,

I encountered the same issue while trying to run this project. I managed to resolve it by using Python 3.8. It seems that there might be compatibility issues with other Python versions, so switching to Python 3.8 could be a potential solution for anyone experiencing similar problems.

Hope this helps!

**Comment by KennethEladistu** [comment]
you can solve this by doing pip install ocrd-fork-pylsd hehe
