### ISSUE TITLE
Implementation has been removed due to original code license issues

### ISSUE THREAD

**Issue by akkitech** [andrewdcampbell/OpenCV-Document-Scanner#4]
I am receiving below error while executing python scan.py --images imageDirectory

Traceback (most recent call last):
  File "scan.py", line 335, in <module>
    scanner.scan(im_dir + '/' + im)
  File "scan.py", line 284, in scan
    screenCnt = self.get_contour(rescaled_image)
  File "scan.py", line 198, in get_contour
    test_corners = self.get_corners(edged)
  File "scan.py", line 95, in get_corners
    lsd = cv2.createLineSegmentDetector()
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\lsd.cpp:143: error: (-213:The function/feature is not implemented) Implementation has been removed due original code license issues in function 'cv::LineSegmentDetectorImpl::LineSegmentDetectorImpl'

Python version : 3.7.3
OpenCV version : 4.1.0

Is there any workaround for this issue?

Thanks.

**Comment by AchuThanFinstreet** [comment]
I got the same issue. Some solution here?

**Comment by AchuThanFinstreet** [comment]
After uninstalling current opencv-version and reinstalling old one (3.1.0.0) it works now without this error.

**Comment by tangjie77wd** [comment]
I got the same issue even if i choosed 'OPENCV_ENABLE_NONFEE' ! Someone told me his solution----re-run CMAKE with WITH_WIN32UI, since you are on Windows, and eventually with WITH_QT.

**Comment by barabanus** [comment]
It looks like LSD detector had been removed completely from the source tree (see 3ba49ccecc773592a3e8d68ad9f5b06196dae6b6) =(

**Comment by tangjie77wd** [comment]
@akkitech @AchuThanFinstreet @barabanus I have solved my problem with the following solution :
#include <opencv2/ximgproc.hpp>
#include <opencv2/line_descriptor/descriptor.hpp> 
using namespace cv::ximgproc;
{	
...	
vector<Vec4f> lines;	
Ptr<cv::ximgproc::FastLineDetector> detector = cv::ximgproc::createFastLineDetector();	
detector->detect(roi, lines);
}
I have test it succeessfully.BTW,LSD detector has not been removed from opencv 4.10 but removed to cv::ximgproc from cv !

**Comment by barabanus** [comment]
Thanks, @tangjie77wd ! `ximgproc` is contributed module. If you look at the commit I mentioned LSD was physically removed from 4.1.0.

**Comment by tangjie77wd** [comment]
@barabanus  Opencv shows an example [https://docs.opencv.org/4.1.0/d1/d9e/fld_lines_8cpp-example.html](url)  which supports both LSD and FastLineDetector.How could they draw lines in the example if they did not imcomplete LSD ? Well ,I will try once i am free.

**Comment by nyamba** [comment]
> 
> 
> After uninstalling current opencv-version and reinstalling old one (3.1.0.0) it works now without this error.

this is works to me. thanks!

**Comment by frohro** [comment]
Same issue here on Ubuntu 19.04.

**Comment by maky-hnou** [comment]
had the same issue with `opencv-contrib-python==4.1.1.26` and `opencv-python==4.1.1.26`.  
**The solutions** I ended to are: 

- Downgrade to `opencv-contrib-python==4.0.0.21` and `opencv-python==4.0.0.21`.  

- According to this [question](https://stackoverflow.com/questions/56016650/how-to-implement-lsd-in-opencv-4-1-0) on Stakoverflow, to replace the missing `LineSegmentDetectorImpl`, install pylsd using `pip install pylsd`. For more details about how to use it with opencv, please check [the documentation](https://github.com/primetang/LSD-OpenCV-MATLAB/tree/master/pylsd).

**Comment by Tsypaev** [comment]
It work with opencv-python version 4.1.1.26 too.

**Comment by ruelj2** [comment]
I suggest you all add a thumbs-up to this issue!  
"Restore LineSegmentDetector LSD & avoid license conflict"  
[issue-615242133](https://github.com/opencv/opencv_contrib/issues/2524#issue-615242133)
